version: '3'
services:
  app:
    # main builder app
    build:
      context: .
    volumes:
      - ./src:/app:delegated
      - ./.local:/app/.local:delegated
    links:
      - echoserver
      - db
    depends_on:
      - echoserver
      - db
    environment:
      CACHE_CONTROL: max-age=60
      USER_ENVIRONMENT_VARIABLE_KEY: shhhhhhh
      # NO_SERVICES: 'True'

      # Required only if NO_SERVICES is not 'True'
      FEDERALIST_BUILDER_CALLBACK: http://echoserver:8989/builder
      STATUS_CALLBACK: http://echoserver:8989/status

      # Optional, if provided AND NO_SERVICES is not 'True',
      # logs will be written to database. Note that the database
      # may have to be initialized by running ./bin/migrate.py
      DATABASE_URL: postgresql://postgres@db/federalist

  echoserver:
    # simple python server to log requests during development
    build:
      context: ./echo-server
      dockerfile: ./Dockerfile
    volumes:
      - ./echo-server:/code
    environment:
      PORT: 8989
    ports:
      - "8989:8989"

  db:
    image: postgres:latest
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: federalist
