version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 449ef357d9e81688685bde0dcdd348bc764d717fa6a4c9c01562bd8037ceb665
    machine: true
    steps:
      - checkout

      - run:
          name: Build docker image
          command: |
            docker build -t federalist-garden-build .

      - run:
          name: Start docker container
          command: |
            docker run --name fgb -dt federalist-garden-build bash

      - run:
          name: Install test dependencies
          command: |
            docker exec fgb pip install -r requirements-dev.txt

      - run:
          name: Flake8
          command: |
            docker exec fgb flake8

      - run:
          name: Bandit
          command: |
            docker exec fgb bandit publishing/*.py tasks/*.py log_utils/*.py repo_config/*.py

      - run:
          name: Install cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: CodeClimate before-build
          command: ./cc-test-reporter before-build

      - run:
          name: Pytest
          command: |
            docker exec -v ./coverage:/app/coverage fgb pytest

      - run:
          name: CodeClimate after-build
          command: |
            # for whatever reason the current user doesn't have access
            # to the directory that gets created for the docker-compose
            # `coverage/` volume, so `chown` it
            sudo chown -R $(whoami) ./coverage
            ./cc-test-reporter format-coverage -t coverage.py ./coverage/coverage.xml
            ./cc-test-reporter upload-coverage || true

      - store_artifacts:
          path: ./coverage/coverage.xml

