version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t test-image --build-arg is_testing=1 .
      - run:
          name: Docker pytest
          command: |
            docker run --rm -i -t test-image pytest
      - run:
          name: Docker bandit
          command: |
            docker run --rm -i -t test-image bandit -r .
      - run:
          name: Docker flake8
          command: |
            docker run --rm -i -t test-image flake8