version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build -t federalist-garden-build-py:$CIRCLE_BRANCH --build-arg is_testing=1 .
      - run:
          name: Docker pytest
          command: |
            docker run --rm -i -t federalist-garden-build-py:$CIRCLE_BRANCH pytest
      - run:
          name: Docker bandit
          command: |
            docker run --rm -i -t federalist-garden-build-py:$CIRCLE_BRANCH bandit -r .
      - run:
          name: Docker flake8
          command: |
            docker run --rm -i -t federalist-garden-build-py:$CIRCLE_BRANCH flake8