---
############################
#  SHARED

staging-cf: &staging-cf
  CF_API: https://api.fr.cloud.gov
  CF_USERNAME: ((cf-username))
  CF_PASSWORD: ((cf-password))
  CF_ORG: gsa-18f-federalist
  CF_SPACE: staging

python-image: &python-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: python
      tag: 3.8

cf-image: &cf-image
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: 18fgsa/concourse-task


############################
#  JOBS

jobs:
      
  - name: test-staging
    plan:
      - get: src
        resource: src-staging
        trigger: true
        params: {depth: 1}
      - put: gh-status
        inputs: [src]
        params: {state: pending}
      - task: test
        config:
          <<: *python-image
          inputs: [name: src]
          outputs: [name: src]
          run:
            dir: src
            path: src/ci/tasks/test.sh
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: pages build container tests on staging
              ((build-url))
              <@U01J8B463T5> <@U01J0M3E8NS> <@U01J7LKV5MZ>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: deploy-staging
    plan:
      - get: src
        resource: src-staging
        trigger: true
        params: {depth: 1}
        passed: [test-staging]
      - put: build-container-image
        params: {dockerfile: Dockerfile}
      - task: deploy
        config:
          <<: *cf-image
          inputs: [name: src]
          run:
            path: src/ci/tasks/deploy.sh
        params:
          <<: *staging-cf
          CF_APP_NAME: federalist-build-container-staging
          CF_MANIFEST: src/.cloudgov/manifest.yml
          CF_VARS_FILE: src/.cloudgov/vars/staging.yml
          CF_PATH: src
          CF_DOCKER_REGISTRY_URL: ((docker-registry-url))
          CF_DOCKER_IMAGE: ((docker-registry-url))/federalist-staging-ecr:staging
          CF_DOCKER_USERNAME: ((aws-ecr-read-key))
          CF_DOCKER_PASSWORD: ((aws-ecr-read-secret))
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: pages build container deployment on staging
              ((build-url))
              <@U01J8B463T5> <@U01J0M3E8NS> <@U01J7LKV5MZ>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: deploy-staging-exp
    plan:
      - get: src
        resource: src-staging
        trigger: true
        params: {depth: 1}
        passed: [test-staging]
      - put: build-container-image-exp
        params: {dockerfile: Dockerfile-exp}
      - task: deploy
        config:
          <<: *cf-image
          inputs: [name: src]
          run:
            path: src/ci/tasks/deploy.sh
        params:
          <<: *staging-cf
          CF_APP_NAME: federalist-build-container-exp-staging
          CF_MANIFEST: src/.cloudgov/manifest.yml
          CF_VARS_FILE: src/.cloudgov/vars/staging.yml
          CF_PATH: src
          CF_DOCKER_REGISTRY_URL: ((docker-registry-url))
          CF_DOCKER_IMAGE: ((docker-registry-url))/federalist-staging-ecr:staging-exp
          CF_DOCKER_USERNAME: ((aws-ecr-read-key))
          CF_DOCKER_PASSWORD: ((aws-ecr-read-secret))
    on_failure:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: failure}
        - put: slack
          params:
            text: |
              :x: FAILED: pages build container exp deployment on staging
              ((build-url))
              <@U01J8B463T5> <@U01J0M3E8NS> <@U01J7LKV5MZ>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: report-success-staging
    plan:
      - get: src
        resource: src-staging
        trigger: true
        params: {depth: 1}
        passed: [deploy-staging, deploy-staging-exp]
    on_success:
      in_parallel:
        - put: gh-status
          inputs: [src]
          params: {state: success}  
        - put: slack
          params:
            text: |
              :white_check_mark: SUCCESS: Successfully deployed pages build containers on staging
              ((build-url))
              <@U01J8B463T5> <@U01J0M3E8NS> <@U01J7LKV5MZ>
            channel: ((slack-channel))
            username: ((slack-username))
            icon_url: ((slack-icon-url))

  - name: nightly-tasks-staging
    plan:
      - get: src
        resource: src-staging
        params: {depth: 1}
      - get: nightly
        trigger: true
      - task: restage
        config:
          <<: *cf-image
          inputs: [name: src]
          run:
            path: src/ci/tasks/restage.sh
        params:
          <<: *staging-cf
          CF_APP_NAME: federalist-build-container-staging

  - name: nightly-tasks-staging-exp
    plan:
      - get: src
        resource: src-staging
        params: {depth: 1}
      - get: nightly
        trigger: true
      - task: restage
        config:
          <<: *cf-image
          inputs: [name: src]
          run:
            path: src/ci/tasks/restage.sh
        params:
          <<: *staging-cf
          CF_APP_NAME: federalist-build-container-exp-staging


############################
#  RESOURCES

resources:

  - name: src-staging
    type: git
    icon: github
    source:
      uri: https://github.com/18F/federalist-garden-build
      # branch: staging
      branch: dc/concourse

  # - name: src-production
  #   type: git
  #   icon: github
  #   source:
  #     uri: https://github.com/18F/federalist-garden-build
  #     branch: main

  - name: nightly
    type: time
    source:
      start: 12:00 AM
      stop: 1:00 AM
      location: America/New_York

  - name: slack
    type: slack-notification
    source:
      url: ((slack-webhook-url))

  - name: gh-status
    type: cogito
    check_every: 1h
    source:
      owner: 18F
      repo: federalist-garden-build
      access_token: ((gh-access-token))
      context_prefix: concourse

  - name: build-container-image
    type: docker-image
    source:
      repository: ((docker-registry-url))/federalist-staging-ecr
      tag: staging
      aws_access_key_id: ((aws-ecr-write-key))
      aws_secret_access_key: ((aws-ecr-write-secret))
      
  - name: build-container-image-exp
    type: docker-image
    source:
      repository: ((docker-registry-url))/federalist-staging-ecr
      tag: staging-exp
      aws_access_key_id: ((aws-ecr-write-key))
      aws_secret_access_key: ((aws-ecr-write-secret))


############################
#  RESOURCE TYPES

resource_types:

  - name: cogito
    type: docker-image
    check_every: 24h
    source:
      repository: pix4d/cogito

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource